import fs from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
const SESSION="casebook-trial";
async function defaultExecutor(executable,args,options){return await new Promise((resolve,reject)=>{const child=spawn(executable,args,{...options,stdio:["ignore","pipe","pipe"]});let stdout="",stderr="";child.stdout.setEncoding("utf8").on("data",chunk=>stdout+=chunk);child.stderr.setEncoding("utf8").on("data",chunk=>stderr+=chunk);child.once("error",reject);child.once("close",status=>resolve({status,stdout,stderr}));});}
function json(output,operation){try{return JSON.parse(output);}catch{throw new Error(`${operation} returned invalid JSON`);}}
function string(value){return typeof value==="string"&&value.length>0;}
function integer(value,{positive=false}={}){return Number.isSafeInteger(value)&&value>=(positive?1:0);}
const AGENT_STATUSES=new Set(["idle","working","blocked","done","unknown"]);
function agentStatus(value){return AGENT_STATUSES.has(value);}
function stringMap(value){return value===undefined||(value!==null&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).length<=32&&Object.entries(value).every(([key,item])=>/^[A-Za-z0-9_-]{1,32}$/.test(key)&&typeof item==="string"));}
function optionalString(value){return value==null||typeof value==="string";}
function validateWorkspace(value,operation="workspace"){
  if(!value||!string(value.workspace_id)||!integer(value.number,{positive:true})||typeof value.label!=="string"||typeof value.focused!=="boolean"||!integer(value.pane_count,{positive:true})||!integer(value.tab_count,{positive:true})||!string(value.active_tab_id)||!agentStatus(value.agent_status)||!stringMap(value.tokens))throw new Error(`${operation} returned an invalid workspace`);
  if(value.worktree!=null){const w=value.worktree;if(!string(w.repo_key)||!string(w.repo_name)||!string(w.repo_root)||!string(w.checkout_path)||typeof w.is_linked_worktree!=="boolean")throw new Error(`${operation} returned an invalid worktree`);}
  return value;
}
function validateTab(value,operation="tab") {if(!value||!string(value.tab_id)||!string(value.workspace_id)||!integer(value.number,{positive:true})||typeof value.label!=="string"||typeof value.focused!=="boolean"||!integer(value.pane_count,{positive:true})||!agentStatus(value.agent_status))throw new Error(`${operation} returned an invalid tab`);return value;}
function validateAgentSession(value){return value==null||(string(value.source)&&string(value.agent)&&["session_id","session_path"].includes(value.kind)&&string(value.value));}
function validatePane(value,operation="pane") {if(!value||!string(value.pane_id)||!string(value.terminal_id)||!string(value.workspace_id)||!string(value.tab_id)||typeof value.focused!=="boolean"||!agentStatus(value.agent_status)||!validateAgentSession(value.agent_session)||!optionalString(value.cwd)||!optionalString(value.foreground_cwd)||!optionalString(value.label)||!optionalString(value.agent)||!optionalString(value.title)||!optionalString(value.terminal_title)||!optionalString(value.terminal_title_stripped)||!optionalString(value.display_agent)||!stringMap(value.state_labels)||!stringMap(value.tokens)||!integer(value.revision))throw new Error(`${operation} returned an invalid pane`);return value;}
function validateAgent(value,index){if(!value||!string(value.terminal_id)||!string(value.workspace_id)||!string(value.tab_id)||!string(value.pane_id)||typeof value.focused!=="boolean"||!agentStatus(value.agent_status)||!validateAgentSession(value.agent_session)||!stringMap(value.state_labels)||!stringMap(value.tokens))throw new Error(`agent list returned an invalid agent at ${index}`);return value;}
export function parseWorkspaceListResponse(output){const response=json(output,"workspace list");if(response?.result?.type!=="workspace_list"||!Array.isArray(response.result.workspaces))throw new Error("workspace list returned an unexpected response");const seen=new Set();return response.result.workspaces.map((value,index)=>{const workspace=validateWorkspace(value,`workspace list[${index}]`);if(seen.has(workspace.workspace_id))throw new Error(`workspace list returned duplicate workspace ID: ${workspace.workspace_id}`);seen.add(workspace.workspace_id);return workspace;});}
export function parseAgentListResponse(output){const response=json(output,"agent list");if(response?.result?.type!=="agent_list"||!Array.isArray(response.result.agents))throw new Error("agent list returned an unexpected response");return response.result.agents.map(validateAgent);}
export function createHerdrClient({env=process.env,route,executor=defaultExecutor,realpath=fs.realpath}){
  if(!path.isAbsolute(env.HERDR_BIN_PATH??""))throw new Error("HERDR_BIN_PATH must be an absolute executable path");if(route?.sessionName!==SESSION)throw new Error(`route must be ${SESSION}`);if(route.configPath&&env.HERDR_CONFIG_PATH!==route.configPath)throw new Error("inherited config proof does not match registry");if(route.socketPath&&env.HERDR_SOCKET_PATH!==route.socketPath)throw new Error("inherited socket proof does not match registry");
  const call=async(args,operation)=>{let result;try{result=await executor(env.HERDR_BIN_PATH,["--session",SESSION,...args],{env:{...env},shell:false});}catch(error){throw new Error(`${operation} delivery uncertain: ${error.message}`);}if(result?.status!==0)throw new Error(`${operation} failed or uncertain (exit ${result?.status??"unknown"})`);return result.stdout??"";};
  return{
    async listWorkspaces(){return parseWorkspaceListResponse(await call(["workspace","list"],"workspace list"));},
    async listAgents(){return parseAgentListResponse(await call(["agent","list"],"agent list"));},
    async getPane(paneId){if(!string(paneId))throw new TypeError("pane ID is required");const response=json(await call(["pane","get",paneId],"pane get"),"pane get");if(response?.result?.type!=="pane_info")throw new Error("pane get returned an unexpected response");const pane=validatePane(response.result.pane,"pane get");if(pane.pane_id!==paneId)throw new Error("pane get response target mismatch");return pane;},
    async focusWorkspace(workspaceId){if(!string(workspaceId))throw new TypeError("workspace ID is required");const response=json(await call(["workspace","focus",workspaceId],"workspace focus"),"workspace focus"),workspace=validateWorkspace(response?.result?.workspace,"workspace focus");if(response?.result?.type!=="workspace_info"||workspace.workspace_id!==workspaceId||workspace.focused!==true)throw new Error("workspace focus response target mismatch");return workspace;},
    async createWorkspace(cwd,label){if(!string(cwd)||!string(label))throw new TypeError("workspace cwd and label are required");const expectedRoot=await realpath(cwd);const response=json(await call(["workspace","create","--cwd",expectedRoot,"--label",label,"--focus"],"workspace create"),"workspace create");if(response?.result?.type!=="workspace_created")throw new Error("workspace create returned an unexpected response");const workspace=validateWorkspace(response.result.workspace,"workspace create"),tab=validateTab(response.result.tab,"workspace create"),rootPane=validatePane(response.result.root_pane,"workspace create");
      if(workspace.label!==label||workspace.focused!==true||workspace.active_tab_id!==tab.tab_id||tab.workspace_id!==workspace.workspace_id||tab.focused!==true||rootPane.workspace_id!==workspace.workspace_id||rootPane.tab_id!==tab.tab_id||rootPane.focused!==true||!rootPane.cwd)throw new Error("workspace create response relationship mismatch");
      let paneRoot;try{paneRoot=await realpath(rootPane.cwd);}catch{throw new Error("workspace create root pane cwd is unavailable");}if(paneRoot!==expectedRoot)throw new Error("workspace create root pane cwd mismatch");return{workspace,tab,rootPane:{...rootPane,cwd:paneRoot}};
    },
    async openPicker(){const response=json(await call(["plugin","pane","open","--plugin","aryk.spaces","--entrypoint","spaces","--placement","popup"],"plugin pane open"),"plugin pane open");if(response?.result?.type!=="ok")throw new Error("plugin pane open returned an unexpected response");return{status:"opened"};},
  };
}
