import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
let counter=0;const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function text(value,field){if(typeof value!=="string"||value.trim()==="")throw new TypeError(`${field} is required`);return value;}
export function pathsFor(env=process.env){const home=env.HOME||os.homedir(),configHome=env.XDG_CONFIG_HOME||path.join(home,".config"),stateHome=env.XDG_STATE_HOME||path.join(home,".local","state");if(!path.isAbsolute(configHome)||!path.isAbsolute(stateHome))throw new Error("XDG roots must be absolute");const trialState=path.join(stateHome,"agent-os","herdr-trials","casebook");return{config:path.join(configHome,"herdr","trials","casebook","spaces.json"),registry:path.join(trialState,"bindings","registry.json"),stateRoot:path.join(trialState,"spaces"),pending:path.join(trialState,"spaces","pending-enrollments.json"),plainBindings:path.join(trialState,"spaces","plain-workspaces.json")};}
export async function assertNoSymlink(file){if(!path.isAbsolute(file))throw new Error("path must be absolute");const normalized=path.normalize(file),parsed=path.parse(normalized);let current=parsed.root;for(const part of normalized.slice(parsed.root.length).split(path.sep).filter(Boolean)){current=path.join(current,part);try{if((await fs.lstat(current)).isSymbolicLink())throw new Error(`path contains symlink: ${current}`);}catch(error){if(error.code!=="ENOENT")throw error;}}}
async function prepareParent(file){await assertNoSymlink(path.dirname(file));await fs.mkdir(path.dirname(file),{recursive:true,mode:0o700});await assertNoSymlink(path.dirname(file));if(await fs.realpath(path.dirname(file))!==path.normalize(path.dirname(file)))throw new Error("state parent canonical path mismatch");}
export async function atomicWriteJson(file,value){await prepareParent(file);const temp=path.join(path.dirname(file),`.${path.basename(file)}.${process.pid}.${Date.now()}.${counter++}.tmp`);let handle;try{handle=await fs.open(temp,"wx",0o600);await handle.writeFile(`${JSON.stringify(value,null,2)}\n`);await handle.sync();await handle.close();handle=null;await assertNoSymlink(path.dirname(file));await fs.rename(temp,file);const dir=await fs.open(path.dirname(file),"r");try{await dir.sync();}finally{await dir.close();}}catch(error){if(handle)await handle.close().catch(()=>{});await fs.rm(temp,{force:true}).catch(()=>{});throw error;}}
export async function readJson(file,fallback){await assertNoSymlink(file);try{return JSON.parse(await fs.readFile(file,"utf8"));}catch(error){if(error.code==="ENOENT"&&fallback!==undefined)return structuredClone(fallback);throw error;}}
async function locked(file,operation,{attempts=200,delayMs=5}={}){const lock=`${file}.lock`;await prepareParent(lock);let handle;for(let attempt=0;attempt<attempts;attempt++){try{handle=await fs.open(lock,"wx",0o600);break;}catch(error){if(error.code!=="EEXIST")throw error;if(attempt===attempts-1)throw new Error(`state lock unavailable: ${lock}`);await sleep(delayMs);}}const held=await handle.stat();try{return await operation();}finally{let current=null;try{current=await fs.lstat(lock);}catch{}await handle.close();if(current&&current.dev===held.dev&&current.ino===held.ino)await fs.unlink(lock);}}
export async function atomicPendingEnrollment(file,request,lockOptions){text(request?.canonicalProjectId,"canonicalProjectId");text(request?.requestedAt,"requestedAt");return locked(file,async()=>{const value=await readJson(file,{schemaVersion:1,requests:[]});if(value?.schemaVersion!==1||!Array.isArray(value.requests))throw new Error("invalid pending enrollment state");if(!value.requests.some(item=>item?.canonicalProjectId===request.canonicalProjectId))value.requests.push(structuredClone(request));await atomicWriteJson(file,value);return value;},lockOptions);}
export function validatePlainEvidence(value){const evidence={workspaceId:text(value?.workspaceId,"workspaceId"),tabId:text(value?.tabId,"tabId"),paneId:text(value?.paneId,"paneId"),terminalId:text(value?.terminalId,"terminalId"),rootRealpath:text(value?.rootRealpath,"rootRealpath")};if(!path.isAbsolute(evidence.rootRealpath))throw new TypeError("rootRealpath must be absolute");return evidence;}
export function parsePlainBindings(value){if(value?.schemaVersion!==2||!value.bindings||typeof value.bindings!=="object"||Array.isArray(value.bindings))throw new Error("unsupported plain workspace binding state");const bindings={};for(const [key,evidence] of Object.entries(value.bindings)){const parsed=validatePlainEvidence(evidence);if(key!==parsed.workspaceId)throw new Error("plain binding key mismatch");bindings[key]=parsed;}return{schemaVersion:2,bindings};}
export async function savePlainBinding(file,evidenceValue,lockOptions){const evidence=validatePlainEvidence(evidenceValue);return locked(file,async()=>{let value;try{value=await readJson(file);}catch(error){if(error.code!=="ENOENT")throw error;}if(value?.schemaVersion===1)value=undefined;const parsed=value?parsePlainBindings(value):{schemaVersion:2,bindings:{}};parsed.bindings[evidence.workspaceId]=evidence;await atomicWriteJson(file,parsed);return parsed;},lockOptions);}
