import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { buildRows,canonicalAllowedPath,planSelection,validateRegistry } from "./core.mjs";
import { createHerdrClient } from "./herdr.mjs";
import { atomicPendingEnrollment,parsePlainBindings,pathsFor,readJson,savePlainBinding } from "./io.mjs";
import { chooseRow,findExecutable,previewPath } from "./picker.mjs";
const DEFAULT_ROOTS=[{path:"~/workspace",depth:2},{path:"~/.config",depth:1},{path:"~/.local/bin/scripts",depth:1}];
const DEFAULT_IGNORES=[".git","node_modules",".venv","vendor","target","dist","build"];
function expandHome(value,home){if(typeof value!=="string")throw new Error("root path must be a string");return value==="~"?home:value.startsWith("~/")?path.join(home,value.slice(2)):value;}
export function defaultConfig(env=process.env){const home=env.HOME||os.homedir();return{schemaVersion:1,roots:DEFAULT_ROOTS.map(root=>({...root,path:expandHome(root.path,home)})),ignores:[...DEFAULT_IGNORES],zoxide:true};}
export function validateConfig(value,env=process.env){if(!value||value.schemaVersion!==1||!Array.isArray(value.roots)||!Array.isArray(value.ignores))throw new Error("invalid spaces config");const home=env.HOME||os.homedir();const roots=value.roots.map((root,index)=>{const resolved=expandHome(root?.path,home);if(!path.isAbsolute(resolved)||!Number.isInteger(root?.depth)||root.depth<0||root.depth>2)throw new Error(`invalid roots[${index}]`);return{path:resolved,depth:root.depth};});if(value.ignores.some(item=>typeof item!=="string"||!item||item.includes(path.sep)||item==="."||item===".."))throw new Error("invalid ignores");if(value.zoxide!=null&&typeof value.zoxide!=="boolean")throw new Error("invalid zoxide setting");return{schemaVersion:1,roots,ignores:[...value.ignores],zoxide:value.zoxide!==false};}
async function physicalRoots(config){const roots=[];for(const item of config.roots){try{const real=await fs.realpath(item.path),stat=await fs.lstat(real);if(stat.isDirectory()&&!roots.some(root=>root.path===real))roots.push({...item,path:real});}catch{}}return roots;}
async function discoverAt(current,remaining,ignores,rows){let entries;try{entries=await fs.readdir(current,{withFileTypes:true});}catch{return;}for(const entry of entries.sort((a,b)=>a.name.localeCompare(b.name))){if(ignores.has(entry.name)||entry.isSymbolicLink()||!entry.isDirectory())continue;const child=path.join(current,entry.name);let stat;try{stat=await fs.lstat(child);}catch{continue;}if(!stat.isDirectory()||stat.isSymbolicLink())continue;rows.push({path:child,source:"discovered"});if(remaining>1)await discoverAt(child,remaining-1,ignores,rows);}}
export async function discoverFolders(roots,ignores){const rows=[];for(const root of roots){rows.push({path:root.path,source:"configured"});if(root.depth>0)await discoverAt(root.path,root.depth,new Set(ignores),rows);}return rows;}
async function exec(executable,args,options){return await new Promise((resolve,reject)=>{const child=spawn(executable,args,{...options,shell:false,stdio:["ignore","pipe","ignore"]});let stdout="";child.stdout.setEncoding("utf8").on("data",chunk=>stdout+=chunk);child.once("error",reject);child.once("close",status=>resolve({status,stdout}));});}
export async function zoxideFolders(roots,{env=process.env,find=findExecutable,executor=exec}={}){const executable=await find("zoxide",env);if(!executable)return[];let result;try{result=await executor(executable,["query","-l"],{shell:false});}catch{return[];}if(result?.status!==0)return[];const rows=[];for(const line of String(result.stdout??"").split(/\r?\n/).filter(Boolean)){try{rows.push({path:await canonicalAllowedPath(line,roots.map(root=>root.path)),source:"zoxide"});}catch{}}return rows;}
function baseRoute(env){return{sessionName:"casebook-trial",configPath:env.HERDR_CONFIG_PATH,socketPath:env.HERDR_SOCKET_PATH,protocol:17};}
function routeMatches(registry,env){if(registry.route.configPath!==env.HERDR_CONFIG_PATH||registry.route.socketPath!==env.HERDR_SOCKET_PATH)throw new Error("inherited config/socket proof differs from authoritative registry");return registry;}
export async function attestPlainBindings(workspaces,state,allowedRoots,client){
  if(state?.schemaVersion!==2)return{};const parsed=parsePlainBindings(state),active=new Set(workspaces.map(workspace=>workspace.workspace_id)),attested={};
  for(const evidence of Object.values(parsed.bindings)){if(!active.has(evidence.workspaceId))continue;try{const storedRoot=await canonicalAllowedPath(evidence.rootRealpath,allowedRoots),pane=await client.getPane(evidence.paneId);if(pane.workspace_id!==evidence.workspaceId||pane.tab_id!==evidence.tabId||pane.terminal_id!==evidence.terminalId||!pane.cwd)continue;const paneRoot=await canonicalAllowedPath(pane.cwd,allowedRoots);if(paneRoot!==storedRoot)continue;attested[evidence.workspaceId]=storedRoot;}catch{}}
  return attested;
}
async function augmentLive(workspaces,plainState,allowedRoots,client){const bindings=await attestPlainBindings(workspaces,plainState,allowedRoots,client);const augmented=await Promise.all(workspaces.map(async workspace=>{let verifiedRoot=bindings[workspace.workspace_id]??null;if(!verifiedRoot&&workspace.worktree?.checkout_path){try{verifiedRoot=await fs.realpath(workspace.worktree.checkout_path);}catch{}}return{...workspace,verifiedRoot};}));return{bindings,workspaces:augmented};}
async function loadPlain(paths,read){return await read(paths.plainBindings,{schemaVersion:2,bindings:{}});}
async function loadRegistry(paths,env,read){return routeMatches(validateRegistry(await read(paths.registry)),env);}
export async function openSpacesAction({env=process.env,client}={}){const actual=client??createHerdrClient({env,route:baseRoute(env)});await actual.openPicker();return{status:"opened"};}
export async function runPicker({env=process.env,client,choose=chooseRow,preview=previewPath,output=process.stdout,read=readJson,saveBinding=savePlainBinding}={}){
  const paths=pathsFor(env),rawConfig=await read(paths.config,defaultConfig(env)),config=validateConfig(rawConfig,env),roots=await physicalRoots(config);if(!roots.length)throw new Error("No configured allowed folder root is available.");const allowed=roots.map(root=>root.path);
  let registry=null,registryError=null,agents=[];try{registry=await loadRegistry(paths,env,read);}catch(error){registryError=error;}
  const herdr=client??createHerdrClient({env,route:registry?.route??baseRoute(env)}),initialWorkspaces=await herdr.listWorkspaces();
  if(registry){try{agents=await herdr.listAgents();}catch(error){registryError=error;agents=[];}}
  const initialPlain=await loadPlain(paths,read),live=await augmentLive(initialWorkspaces,initialPlain,allowed,herdr),discovered=await discoverFolders(roots,config.ignores),zoxide=config.zoxide?await zoxideFolders(roots,{env}):[];
  const rows=buildRows({registry,liveWorkspaces:live.workspaces,agents,folders:[...discovered,...zoxide],plainBindings:live.bindings});if(registryError)output.write(`Semantic registry unavailable or unattested: ${registryError.message}\n`);
  const choice=await choose(rows);if(choice.status!=="selected"){if(choice.message)output.write(`${choice.message}\n`);return choice;}const selected={...choice.row};
  if(selected.source==="Folder"){selected.path=await canonicalAllowedPath(selected.path,allowed);output.write(`${await preview(selected.path)}\n`);const freshWorkspaces=await herdr.listWorkspaces(),freshPlain=await loadPlain(paths,read),freshLive=await augmentLive(freshWorkspaces,freshPlain,allowed,herdr);const plan=planSelection({...selected,state:"unopened"},freshLive.workspaces);if(plan.kind==="refuse"){output.write(`${plan.message}\n`);return{status:"refused",message:plan.message};}if(plan.kind==="focus"){await herdr.focusWorkspace(plan.workspaceId);return{status:"focused",workspaceId:plan.workspaceId};}
    const created=await herdr.createWorkspace(plan.path,plan.label),evidence={workspaceId:created.workspace.workspace_id,tabId:created.tab.tab_id,paneId:created.rootPane.pane_id,terminalId:created.rootPane.terminal_id,rootRealpath:plan.path};try{await saveBinding(paths.plainBindings,evidence);}catch(error){const message=`Workspace ${evidence.workspaceId} was created and verified, but its local folder attestation could not be written (${error.message}). Do not retry creation; use the Live row or reconcile state.`;output.write(`${message}\n`);return{status:"created-unrecorded",workspaceId:evidence.workspaceId,message};}return{status:"created",workspaceId:evidence.workspaceId};
  }
  if(selected.source==="Live"){const fresh=await herdr.listWorkspaces(),plan=planSelection(selected,fresh);if(plan.kind!=="focus"){output.write(`${plan.message}\n`);return{status:"refused",message:plan.message};}await herdr.focusWorkspace(plan.workspaceId);return{status:"focused",workspaceId:plan.workspaceId};}
  if(selected.source==="Semantic"){let freshRegistry;try{freshRegistry=await loadRegistry(paths,env,read);}catch(error){const message=`Semantic registry unavailable: ${error.message}`;output.write(`${message}\n`);return{status:"refused",message};}const [freshWorkspaces,freshAgents]=await Promise.all([herdr.listWorkspaces(),herdr.listAgents()]),semantic=buildRows({registry:freshRegistry,liveWorkspaces:freshWorkspaces,agents:freshAgents}).find(row=>row.canonicalId===selected.canonicalId),plan=planSelection(semantic,freshWorkspaces);if(plan.kind==="refuse"){output.write(`${plan.message}\n`);return{status:"refused",message:plan.message};}if(plan.kind==="enroll"){await atomicPendingEnrollment(paths.pending,{canonicalProjectId:plan.canonicalProjectId,requestedAt:new Date().toISOString(),reason:"selected-unopened-semantic-project"});const message=`Enrollment requested for ${plan.canonicalProjectId}. A trusted Casebook/Steward publisher must reconcile it; this plugin did not start Steward or mutate Casebook.`;output.write(`${message}\n`);return{status:"pending",message};}await herdr.focusWorkspace(plan.workspaceId);return{status:"focused",workspaceId:plan.workspaceId};}
  const message="Unknown space source.";output.write(`${message}\n`);return{status:"refused",message};
}
