import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createBootstrapAuthorizationDocument } from "../variants/sqlite/lib/substrate/bootstrap.mjs";
import { selectSqliteBinary, sqlite } from "../variants/sqlite/lib/substrate/diagnostics.mjs";
import { invokeContextOperation, canonicalContextRequestDigest } from "../variants/sqlite/lib/context/index.mjs";

const protocol={id:"casebook-persistence-json",version:2};
const id=(kind,n)=>`${kind}:40000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const I={store:id("store",1),workspace:id("workspace",2),namespace:"namespace:root",nsrev:id("owner-revision",4),nsversion:id("version",5),profile:id("profile",6),prev:id("owner-revision",7),pversion:id("version",8),selection:id("profile-selection",9),srev:id("owner-revision",10),sversion:id("version",11),slot:id("admission-slot",12),event:id("event",13)};
const digest=(x)=>{ const { successorDigest } = globalThis.__context_test ?? {}; return x; };
async function fixture(t) { const root=await mkdtemp(path.join(os.tmpdir(),"casebook-context-"));t.after(()=>rm(root,{recursive:true,force:true})); const store=path.join(root,"context.sqlite3"),grant=path.join(root,"grant.json"); const { successorDigest }=await import("../variants/sqlite/lib/substrate/mechanical-successor.mjs"); const record=(owner_id,revision_id,version_id,content)=>({owner_id,revision_id,version_id,content,content_digest:successorDigest(content)}); const profile={schema:"admission-disclosure-profile@1",audience_ceiling:"private",lifecycle:"active",predecessor_revision_id:null,object_kinds:["profile","profile-selection","namespace","project-default","chat"],purposes:["profile.manage","profile.read","context.manage","context.read"],bounds:{max_results:10,max_traversal_depth:8,max_export_bytes:1000},projection:{locator:"redacted",export:"deny"},disclosure:{receipts:true,events:true,checkpoints:true}}; const req={protocol,operation:"initialize_store",request_version:1,operation_id:"operation:context:init",store_id:I.store,workspace_id:I.workspace,authority_claim:{human_authorized:true,local_uid:process.getuid(),human_identity:"test",provenance:"test"},initial:{root_namespace:record(I.namespace,I.nsrev,I.nsversion,{schema:"namespace-bootstrap@1",display_name:"Root",parent_id:null,lifecycle:"active"}),private_profile:record(I.profile,I.prev,I.pversion,profile),profile_selection:record(I.selection,I.srev,I.sversion,{schema:"profile-selection@1",admission_slot_id:I.slot,selected_profile_id:I.profile,selected_profile_revision_id:I.prev,lifecycle:"active",activation_fence:1}),project_default:null,initialization_event_id:I.event},configuration:{source:{kind:"test",locator:"context"},authority_mode:"sqlite",sqlite:{database_url:store}}}; const auth=await createBootstrapAuthorizationDocument(req,{grant_path:grant});req.request_digest=auth.request_digest;req.bootstrap_authorization={path:grant,sha256:auth.sha256};await writeFile(grant,`${JSON.stringify(auth.document)}\n`,{mode:0o600}); const {execFile}=await import("node:child_process");const entry=path.resolve(new URL("../variants/sqlite/bin/casebook-persistence.mjs",import.meta.url).pathname);await new Promise((resolve,reject)=>{const c=execFile(process.execPath,[entry],{cwd:root,env:{...process.env,HOME:root}},e=>e?reject(e):resolve());c.stdin.end(`${JSON.stringify(req)}\n`);}); return {configuration:req.configuration}; }
function base(fx,operation,op){return {operation,operation_id:op,store_id:I.store,workspace_id:I.workspace,admission_slot_id:I.slot,admission:{kind:"sqlite_profile",binding:{selection_id:I.selection,selection_revision_id:I.srev,profile_id:I.profile,profile_revision_id:I.prev,activation_fence:1}},configuration:fx.configuration};}
function bound(req){req.request_digest=canonicalContextRequestDigest(I.store,req);return req;}
const redactedAccountRef = (suffix) => `redacted-account-ref:v1:sha256:${suffix.toString(16).padStart(64, "0")}`;
async function contextSnapshot(fx) { const binary = await selectSqliteBinary(); const { stdout } = await sqlite(binary, fx.configuration.sqlite.database_url, "PRAGMA query_only=ON; SELECT (SELECT count(*) FROM context_chat_current) chats, (SELECT count(*) FROM context_correlation_claims) correlations, (SELECT count(*) FROM owner_events) events, (SELECT count(*) FROM store_operation_receipts) receipts, (SELECT operation_fence FROM store_fence WHERE singleton=1) fence;", { args: ["-batch", "-bail", "-json"] }); return JSON.parse(stdout)[0]; }
function chatRequest(fx, operation, operationId, chat, suffix, extras = {}) { return bound({ ...base(fx, operation, operationId), chat_id: chat, chat_revision_id: id("owner-revision", suffix), version_id: id("version", suffix + 1), event_id: id("event", suffix + 2), expected_revision: 0, namespace_id: I.namespace, correlation: null, ...extras }); }
test("Context hierarchy, default and Chat binding are explicit and durable",async t=>{const fx=await fixture(t);const child="namespace:personal";let r=await invokeContextOperation(bound({...base(fx,"namespace.create","op:ns"),namespace_id:child,namespace_revision_id:id("owner-revision",21),version_id:id("version",22),event_id:id("event",23),expected_revision:0,parent_namespace_id:I.namespace,display_name:"Child"}));assert.equal(r.ok,true,JSON.stringify(r));r=await invokeContextOperation(bound({...base(fx,"project_default.create","op:default"),project_default_id:id("project-default",24),project_default_revision_id:id("owner-revision",25),version_id:id("version",26),event_id:id("event",27),expected_revision:0,namespace_id:child}));assert.equal(r.ok,true);const chat=id("chat",28);r=await invokeContextOperation(bound({...base(fx,"chat.establish","op:chat"),chat_id:chat,chat_revision_id:id("owner-revision",29),version_id:id("version",30),event_id:id("event",31),expected_revision:0,use_project_default:true,correlation:{correlation_id:id("correlation",32),provider:"test-provider",account_ref:redactedAccountRef(1)}}));assert.equal(r.ok,true,JSON.stringify(r));const resumed=await invokeContextOperation(bound({...base(fx,"chat.resume","op:resume"),chat_id:chat}));assert.equal(resumed.ok,true,JSON.stringify(resumed));assert.equal(resumed.result.status,"resumed");const cycle=await invokeContextOperation(bound({...base(fx,"namespace.revise","op:cycle"),namespace_id:child,namespace_revision_id:id("owner-revision",33),version_id:id("version",34),event_id:id("event",35),expected_revision:1,parent_namespace_id:child,display_name:"Child"}));assert.equal(cycle.failure.code,"hierarchy_invalid");const retired=await invokeContextOperation(bound({...base(fx,"namespace.retire","op:retire"),namespace_id:child,namespace_revision_id:id("owner-revision",36),version_id:id("version",37),event_id:id("event",38),expected_revision:1,parent_namespace_id:I.namespace,display_name:"Child"}));assert.equal(retired.ok,true);const readable=await invokeContextOperation({...base(fx,"chat.read","read:retired"),chat_id:chat});assert.equal(readable.result.status,"visible");const rebind=await invokeContextOperation(bound({...base(fx,"chat.rebind","op:rebind"),chat_id:chat,chat_revision_id:id("owner-revision",39),version_id:id("version",40),event_id:id("event",41),expected_revision:1,namespace_id:I.namespace,correlation:null}));assert.equal(rebind.ok,true);});
test("Chat rebind requires an explicitly established Chat and writes nothing otherwise", async (t) => { const fx = await fixture(t), chat = id("chat", 50), request = chatRequest(fx, "chat.rebind", "op:missing-rebind", chat, 51); const before = await contextSnapshot(fx); const result = await invokeContextOperation(request); assert.equal(result.failure.code, "chat_unavailable"); assert.deepEqual(await contextSnapshot(fx), before); });
test("Chat correlation accepts only structural redaction, rejects secrets without write or disclosure, and never reuses claims", async (t) => { const fx = await fixture(t), chat = id("chat", 60), ref = redactedAccountRef(2); const valid = chatRequest(fx, "chat.establish", "op:valid-correlation", chat, 61, { correlation: { correlation_id: id("correlation", 64), provider: "test-provider", account_ref: ref } }); const created = await invokeContextOperation(valid); assert.equal(created.ok, true, JSON.stringify(created)); assert.deepEqual(created.result.correlation, { correlation_id: id("correlation", 64), provider: "test-provider", account_ref: ref }); for (const [index, secret] of [["sk_live_0123456789", "abcdefghijklmnopqrstuv"].join(""), "AKIAIOSFODNN7EXAMPLE", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.signature", "raw-account@example.test"].entries()) { const candidate = chatRequest(fx, "chat.establish", `op:raw-correlation:${index}`, id("chat", 70 + index), 80 + index * 4, { correlation: { correlation_id: id("correlation", 81 + index * 4), provider: "test-provider", account_ref: secret } }); const before = await contextSnapshot(fx), denied = await invokeContextOperation(candidate); assert.equal(denied.failure.code, "correlation_invalid"); assert.equal(JSON.stringify(denied).includes(secret), false); assert.deepEqual(await contextSnapshot(fx), before); } const collision = chatRequest(fx, "chat.establish", "op:correlation-collision", id("chat", 90), 91, { correlation: { correlation_id: id("correlation", 94), provider: "test-provider", account_ref: ref } }); const beforeCollision = await contextSnapshot(fx), deniedCollision = await invokeContextOperation(collision); assert.equal(deniedCollision.failure.code, "correlation_collision"); assert.deepEqual(await contextSnapshot(fx), beforeCollision); const reusedId = chatRequest(fx, "chat.establish", "op:correlation-id-reuse", id("chat", 95), 96, { correlation: { correlation_id: id("correlation", 64), provider: "other-provider", account_ref: redactedAccountRef(3) } }); const beforeReuse = await contextSnapshot(fx), deniedReuse = await invokeContextOperation(reusedId); assert.equal(deniedReuse.failure.code, "correlation_collision"); assert.deepEqual(await contextSnapshot(fx), beforeReuse); });

test("Namespace path resolution uses shared NFC/case-fold names and aliases without enumeration", async (t) => {
  const fx = await fixture(t), child = "namespace:cafe";
  const create = (namespace_id, revision, version, event, display_name, aliases) => bound({ ...base(fx, "namespace.create", `op:namespace-resolve:${namespace_id}`), namespace_id, namespace_revision_id: id("owner-revision", revision), version_id: id("version", version), event_id: id("event", event), expected_revision: 0, parent_namespace_id: I.namespace, display_name, aliases });
  assert.equal((await invokeContextOperation(create(child, 111, 112, 113, "Café", ["Alpha"]))).ok, true);
  const resolve = (path) => invokeContextOperation({ ...base(fx, "namespace.resolve", `read:namespace-resolve:${path.join("/")}`), path });
  const found = await resolve(["ROOT", "aLpHa"]);
  assert.equal(found.ok, true, JSON.stringify(found)); assert.equal(found.result.status, "found"); assert.equal(found.result.namespace.id, child); assert.ok(found.result.operation_fence > 0);
  assert.equal((await invokeContextOperation(create("namespace:other", 115, 116, 117, "Other", ["alpha"]))).ok, true);
  const ambiguous = await resolve(["root", "ALPHA"]);
  assert.equal(ambiguous.result.status, "ambiguous"); assert.equal("namespace" in ambiguous.result, false); assert.equal(JSON.stringify(ambiguous.result).includes(child), false);
  const zero = await resolve(["root", "missing"]); assert.equal(zero.result.status, "zero");
});
