import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { cleanupSandbox, generateAndValidateSandbox, selectCompatibleSqliteBinary } from "./sandbox-harness.mjs";

const entrypoint=new URL("../variants/sqlite/bin/casebook-persistence.mjs",import.meta.url).pathname;
const protocol={id:"casebook-persistence-json",version:1};
const IDs=["case:cf1a6369-5713-427b-ad07-001f10a43a4f","case:32031f4b-5b91-4ecd-9727-77af316992e7","case:5a36eb98-867d-404f-a1ce-afb81be92ddc"];
function invoke(cwd,request,binary=entrypoint,extraEnv={}){return new Promise(resolve=>{const child=execFile(process.execPath,[binary],{cwd,env:{PATH:process.env.PATH??"",HOME:cwd,...extraEnv}},(error,stdout,stderr)=>resolve({code:error?2:0,json:JSON.parse(stdout),stderr}));child.stdin.end(JSON.stringify(request));});}
async function setup(){const root=await mkdtemp(path.join(os.tmpdir(),"case-l02-w02-")),bin=await selectCompatibleSqliteBinary(),configuration={source:{kind:"test",locator:"l02-w02"},authority_mode:"sqlite",sqlite:{database_url:path.join(root,"store.db"),sqlite_bin:bin}};const init=await invoke(root,{protocol,operation:"initialize_store",operation_id:"operation:l02-w02-init",authority_claim:{human_authorized:true,acting_role:"architect",authority_basis:"test"},configuration});assert.equal(init.code,0,init.stderr);const i=init.json.result.initialization,context={view_id:i.view.id,view_policy_revision_id:i.view.policy_revision_id,purpose:"scoped discovery",requested_audience_ceiling:"private"};return{root,configuration,i,context};}
const base=(s,id,title,alias)=>({id,home_namespace_id:s.i.namespace.id,state:"active",title,summary:`${title} lexical summary`,scope:"test",aliases:alias?[{id:`alias:${id.slice(5)}`,state:"active",version:{value:alias,kind:"lookup"}}]:[],facets:[],entries:[],sources:[],relationships:[],references:[]});
const common=s=>({protocol,request_version:1,store_id:s.i.store_id,context:s.context,configuration:s.configuration});
async function create(s,id,title,alias){return invoke(s.root,{...common(s),operation:"case.create",operation_id:`operation:create-${id}`,expected_revision:0,commit_basis:"test",provenance:{acting_role:"test"},case:base(s,id,title,alias)});}

test("exact ID/namespace alias resolution and cohesive current/history reads do not mutate",async()=>{const s=await setup();try{const c=await create(s,IDs[0],"Alpha Current","Alpha Alias");assert.equal(c.code,0,JSON.stringify(c.json));const next=base(s,IDs[0],"Alpha Revised","Alpha Alias");next.aliases=[{id:`alias:${IDs[0].slice(5)}`,state:"active",selected_version_id:c.json.result.revision.version_ids[`alias:${IDs[0].slice(5)}`]}];const u=await invoke(s.root,{...common(s),operation:"case.commit_revision",operation_id:"operation:revise-alpha",expected_revision:1,commit_basis:"test",provenance:{acting_role:"test"},case:next});assert.equal(u.code,0,JSON.stringify(u.json));const resolved=await invoke(s.root,{...common(s),operation:"case.resolve",alias:{namespace_id:s.i.namespace.id,value:" alpha alias ",kind:"lookup"}});assert.equal(resolved.json.result.case_id,IDs[0]);const current=await invoke(s.root,{...common(s),operation:"case.read",case_id:IDs[0]});const byNumber=await invoke(s.root,{...common(s),operation:"case.read",case_id:IDs[0],revision_number:1});const byId=await invoke(s.root,{...common(s),operation:"case.read",case_id:IDs[0],revision_id:c.json.result.revision.id});assert.equal(current.json.result.case.title,"Alpha Revised");assert.equal(byNumber.json.result.case.title,"Alpha Current");assert.deepEqual(byNumber.json.result.case,byId.json.result.case);assert.equal((await invoke(s.root,{...common(s),operation:"case.read",case_id:IDs[0]})).json.result.revision.number,2);}finally{await rm(s.root,{recursive:true,force:true});}});

test("lexical search has deterministic paging, query-bound cursors, stale fence rejection, and no ranking",async()=>{const s=await setup();try{await create(s,IDs[0],"Zulu Shared");await create(s,IDs[1],"Alpha Shared");await create(s,IDs[2],"Beta Shared");const first=await invoke(s.root,{...common(s),operation:"case.search",query:"shared",limit:2});assert.deepEqual(first.json.result.items.map(x=>x.title),["Alpha Shared","Beta Shared"]);assert.equal(first.json.result.result_completeness,"truncated");assert.equal(first.json.result.index_implementation,"bounded_hydrated_case_scan");assert.equal(first.json.result.examined_case_count,3);const second=await invoke(s.root,{...common(s),operation:"case.search",query:"shared",limit:2,cursor:first.json.result.next_cursor});assert.deepEqual(second.json.result.items.map(x=>x.title),["Zulu Shared"]);const mismatch=await invoke(s.root,{...common(s),operation:"case.search",query:"alpha",limit:2,cursor:first.json.result.next_cursor});assert.equal(mismatch.code,2);await create(s,"case:0ce1ad39-0dec-4d53-ab98-feb676148ba1","Delta Shared");const stale=await invoke(s.root,{...common(s),operation:"case.search",query:"shared",limit:2,cursor:first.json.result.next_cursor});assert.equal(stale.code,2);}finally{await rm(s.root,{recursive:true,force:true});}});

test("explicit reference traversal handles direction, depth, cycles and node-limit truncation",async()=>{const s=await setup();try{const made=[];for(let i=0;i<3;i++)made.push(await create(s,IDs[i],`Node ${i}`));for(let i=0;i<3;i++){const c=base(s,IDs[i],`Node ${i}`);c.relationships=[{id:["relationship:409931e3-a505-42aa-a6f8-ebbb5fb7133a","relationship:37c39758-feee-4fbb-94ce-dbbcf0c41a58","relationship:b5a648bf-22d0-4c38-a5d3-dc61e9ab0627"][i],state:"active",version:{subject:{kind:"case",id:IDs[i]},predicate:"next",object:{kind:"case",id:IDs[(i+1)%3]},visibility:"private"}}];const r=await invoke(s.root,{...common(s),operation:"case.commit_revision",operation_id:`operation:link-${i}`,expected_revision:1,commit_basis:"links",provenance:{acting_role:"test"},case:c});assert.equal(r.code,0,JSON.stringify(r.json));}const out=await invoke(s.root,{...common(s),operation:"case.traverse",start_case_ids:[IDs[0]],predicates:["next"],direction:"outgoing",max_depth:8,node_limit:10});assert.deepEqual(out.json.result.nodes.map(x=>x.depth),[0,1,2]);assert.deepEqual(out.json.result.nodes.map(x=>x.kind),["case","case","case"]);assert.equal(out.json.result.result_completeness,"complete_within_bounds");assert.equal(out.json.result.edges.length,3,"cycle-closing edge is retained even though its node is already expanded");const incoming=await invoke(s.root,{...common(s),operation:"case.traverse",start_case_ids:[IDs[0]],predicates:["next"],direction:"incoming",max_depth:1,node_limit:10});assert.equal(incoming.json.result.nodes.some(x=>x.kind==="case"&&x.id===IDs[2]),true);const cut=await invoke(s.root,{...common(s),operation:"case.traverse",start_case_ids:[IDs[0]],predicates:["next"],direction:"outgoing",max_depth:8,node_limit:2});assert.equal(cut.json.result.result_completeness,"truncated");assert.equal(cut.json.result.truncation_reason,"node_limit");}finally{await rm(s.root,{recursive:true,force:true});}});

test("unknown and invalid selectors are non-leaking and non-mutating",async()=>{const s=await setup();try{await create(s,IDs[0],"Visible");const unknown=await invoke(s.root,{...common(s),operation:"case.resolve",case_id:IDs[1]});assert.equal(unknown.json.failure.code,"case.not_found_or_not_visible");assert.deepEqual(unknown.json.failure.evidence,{});const invalid=await invoke(s.root,{...common(s),operation:"case.search",query:"visible",limit:51});assert.equal(invalid.code,2);const read=await invoke(s.root,{...common(s),operation:"case.read",case_id:IDs[0]});assert.equal(read.json.result.revision.number,1);}finally{await rm(s.root,{recursive:true,force:true});}});

test("generated Pi, Codex, and OpenCode commands execute Case discovery",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"case-l02-w02-generated-"));try{const report=await generateAndValidateSandbox({sandboxRoot:root});for(const generated of report.results){const cwd=path.join(root,"unrelated-cwd"),binary=path.join(generated.package_root,"variants/sqlite/bin/casebook-persistence.mjs"),configuration={source:{kind:"test",locator:"generated"},authority_mode:"sqlite",sqlite:{database_url:path.join(root,`${generated.target}.db`),sqlite_bin:report.sqlite_binary}};const init=await invoke(cwd,{protocol,operation:"initialize_store",operation_id:`operation:${generated.target}-init`,authority_claim:{human_authorized:true,acting_role:"architect",authority_basis:"test"},configuration},binary);assert.equal(init.code,0,init.stderr);const i=init.json.result.initialization,context={view_id:i.view.id,view_policy_revision_id:i.view.policy_revision_id,purpose:"generated discovery",requested_audience_ceiling:"private"},s={i,context,configuration};const created=await invoke(cwd,{...common(s),operation:"case.create",operation_id:`operation:${generated.target}-create`,expected_revision:0,commit_basis:"generated",provenance:{acting_role:"test"},case:base(s,IDs[0],"Generated Search","generated-alias")},binary);assert.equal(created.code,0,JSON.stringify(created.json));const found=await invoke(cwd,{...common(s),operation:"case.search",query:"generated-alias",limit:5},binary);assert.equal(found.json.result.items[0].case_id,IDs[0],"search examines hydrated aliases, not only projection title/summary");assert.equal(found.json.result.result_completeness,"complete_within_bounds");const old=await invoke(cwd,{...common(s),operation:"case.read",case_id:IDs[0],revision_number:1},binary);assert.equal(old.json.result.case.title,"Generated Search");const missing=await invoke(cwd,{...common(s),operation:"case.resolve",case_id:IDs[1]},binary);assert.equal(missing.json.failure.code,"case.not_found_or_not_visible");assert.deepEqual(missing.json.failure.evidence,{});const absentHistory=await invoke(cwd,{...common(s),operation:"case.read",case_id:IDs[0],revision_number:2},binary);assert.equal(absentHistory.json.failure.code,"case.not_found_or_not_visible");const empty=await invoke(cwd,{...common(s),operation:"case.search",query:"private-never-present",limit:1},binary);assert.deepEqual(empty.json.result.items,[]);const badCursor=await invoke(cwd,{...common(s),operation:"case.search",query:"generated",limit:1,cursor:"not-a-cursor"},binary);assert.equal(badCursor.json.failure.code,"case.invalid_representation");const badTraversal=await invoke(cwd,{...common(s),operation:"case.traverse",start_case_ids:[IDs[0]],predicates:[],direction:"outgoing",max_depth:9,node_limit:1},binary);assert.equal(badTraversal.json.failure.code,"case.invalid_representation");}}finally{assert.equal(await cleanupSandbox(root),true);}});

test("complete lexical corpus covers every selected Case content family and scalar ordering",async()=>{const s=await setup();try{
  const rich=base(s,IDs[0],"Rich Corpus","aliasneedle");
  rich.facets=[{id:"facet:11111111-1111-4111-8111-111111111111",state:"active",version:{key:"facetneedle",value:"facetvalue",visibility:"private"}}];
  rich.entries=[{id:"knowledge:22222222-2222-4222-8222-222222222222",state:"active",version:{display_label:"K1",title:"knowledgeneedle",purpose:"purpose",classification:"accepted",body:"bodyneedle",provenance:{acting_role:"test"},positions:[],relationships:[],references:[]}}];
  rich.sources=[{id:"source:33333333-3333-4333-8333-333333333333",state:"active",display_label:"S1",version:{title:"sourceneedle",author:"author",accessed_at:"2026-01-01T00:00:00Z",examined_for:"examinedneedle",locators:[{kind:"origin",uri:"https://example.test/sourcelocatorneedle",audience:"private"}]},fragments:[{id:"evidence:44444444-4444-4444-8444-444444444444",state:"active",version:{excerpt:"evidenceneedle",purpose:"fragmentpurpose",captured_at:"2026-01-01T00:00:00Z"}}]}];
  rich.relationships=[{id:"relationship:55555555-5555-4555-8555-555555555555",state:"active",version:{subject:{kind:"case",id:IDs[0]},predicate:"relationshipneedle",object:{kind:"knowledge",id:rich.entries[0].id},visibility:"private"}}];
  assert.equal((await invoke(s.root,{...common(s),operation:"case.create",operation_id:"operation:rich",expected_revision:0,commit_basis:"rich",provenance:{acting_role:"test"},case:rich})).code,0);
  for(const q of ["aliasneedle","facetneedle","knowledgeneedle","sourceneedle","evidenceneedle","relationshipneedle"]){const found=await invoke(s.root,{...common(s),operation:"case.search",query:q,limit:5});assert.deepEqual(found.json.result.items.map(x=>x.case_id),[IDs[0]],q);}
  await create(s,IDs[1],"\uE000 scalar");await create(s,IDs[2],"\u{10000} scalar");const ordered=await invoke(s.root,{...common(s),operation:"case.search",query:"scalar",limit:5});assert.deepEqual(ordered.json.result.items.map(x=>x.case_id),[IDs[1],IDs[2]]);
}finally{await rm(s.root,{recursive:true,force:true});}});

test("mixed-kind traversal retains diamond convergence, cycle closure, every edge kind, and strict node limits",async()=>{const s=await setup();try{
  const target=await create(s,IDs[1],"Target");assert.equal(target.code,0);const revision=target.json.result.revision.id;
  const c=base(s,IDs[0],"Graph");const k="knowledge:66666666-6666-4666-8666-666666666666",src="source:77777777-7777-4777-8777-777777777777",ev="evidence:88888888-8888-4888-8888-888888888888",rel="relationship:99999999-9999-4999-8999-999999999999";
  const ref=(predicate)=>({target_kind:"case",target_id:IDs[1],observed_revision_id:revision,predicate});
  c.references=[ref("case-ref")];c.entries=[{id:k,state:"active",version:{display_label:"G1",title:"Graph K",purpose:"graph",classification:"superseded",body:"graph",provenance:{acting_role:"test"},positions:[],relationships:[rel],references:[ref("entry-ref")],supersession:{successor:ref("successor"),basis:[ref("basis")]}}}];
  c.sources=[{id:src,state:"active",display_label:"GS",version:{title:"Graph source",accessed_at:"2026-01-01T00:00:00Z",examined_for:"graph",locators:[{kind:"origin",uri:"https://example.test/graph",audience:"private"}]},fragments:[{id:ev,state:"active",version:{purpose:"graph",captured_at:"2026-01-01T00:00:00Z"}}]}];
  c.relationships=[{id:rel,state:"active",version:{subject:{kind:"case",id:IDs[0]},predicate:"to-k",object:{kind:"knowledge",id:k},visibility:"private"}},{id:"relationship:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",state:"active",version:{subject:{kind:"knowledge",id:k},predicate:"to-source",object:{kind:"source",id:src},visibility:"private"}},{id:"relationship:bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",state:"active",version:{subject:{kind:"knowledge",id:k},predicate:"to-evidence",object:{kind:"evidence",id:ev},visibility:"private"}},{id:"relationship:cccccccc-cccc-4ccc-8ccc-cccccccccccc",state:"active",version:{subject:{kind:"source",id:src},predicate:"diamond",object:{kind:"relationship",id:rel},visibility:"private"}},{id:"relationship:dddddddd-dddd-4ddd-8ddd-dddddddddddd",state:"active",version:{subject:{kind:"evidence",id:ev},predicate:"diamond",object:{kind:"relationship",id:rel},visibility:"private"}},{id:"relationship:eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",state:"active",version:{subject:{kind:"relationship",id:rel},predicate:"cycle",object:{kind:"case",id:IDs[0]},visibility:"private"}}];
  const made=await invoke(s.root,{...common(s),operation:"case.create",operation_id:"operation:graph",expected_revision:0,commit_basis:"graph",provenance:{acting_role:"test"},case:c});assert.equal(made.code,0,JSON.stringify(made.json));
  const out=await invoke(s.root,{...common(s),operation:"case.traverse",start_case_ids:[IDs[0]],predicates:[],direction:"outgoing",max_depth:8,node_limit:20});assert.deepEqual(new Set(out.json.result.nodes.map(x=>x.kind)),new Set(["case","knowledge","source","evidence","relationship"]));assert.equal(out.json.result.nodes.find(x=>x.id===k).owning_case_id,IDs[0]);assert.equal(out.json.result.edges.filter(x=>x.predicate==="diamond").length,2);assert.equal(out.json.result.edges.some(x=>x.predicate==="cycle"),true);assert.deepEqual(new Set(out.json.result.edges.map(x=>x.kind)),new Set(["case_reference","entry_reference","supersession_successor","supersession_basis","relationship"]));
  const cut=await invoke(s.root,{...common(s),operation:"case.traverse",start_case_ids:[IDs[0]],predicates:[],direction:"outgoing",max_depth:8,node_limit:2});assert.equal(cut.json.result.nodes.length,2);assert.equal(cut.json.result.result_completeness,"truncated");assert.equal(cut.json.result.edges.every(x=>x.from_kind&&x.to_kind),true);
}finally{await rm(s.root,{recursive:true,force:true});}});

test("empty and populated corpus fences come from the cohesive SQL snapshot after prepare",async()=>{const s=await setup();try{const empty=await invoke(s.root,{...common(s),operation:"case.search",query:"absent",limit:1},entrypoint,{CASEBOOK_PERSISTENCE_TEST_FAULT:"advance_fence_after_corpus_prepare"});assert.deepEqual(empty.json.result.items,[]);assert.match(empty.json.result.snapshot_query_fence,/^sqlite:\d+$/);const firstFence=Number(empty.json.result.snapshot_query_fence.slice(7));await create(s,IDs[0],"Fence Visible","fence-alias");const resolved=await invoke(s.root,{...common(s),operation:"case.resolve",alias:{namespace_id:s.i.namespace.id,value:"fence-alias",kind:"lookup"}},entrypoint,{CASEBOOK_PERSISTENCE_TEST_FAULT:"advance_fence_after_corpus_prepare"});assert.equal(resolved.json.result.case_id,IDs[0]);const search=await invoke(s.root,{...common(s),operation:"case.search",query:"visible",limit:1});assert.ok(Number(search.json.result.snapshot_query_fence.slice(7))>firstFence);}finally{await rm(s.root,{recursive:true,force:true});}});
