import assert from "node:assert/strict";
import {execFile} from "node:child_process";
import {mkdtemp,rm} from "node:fs/promises";
import os from "node:os";import path from "node:path";import test from "node:test";
import {selectCompatibleSqliteBinary} from "./sandbox-harness.mjs";
const bin=new URL("../variants/sqlite/bin/casebook-persistence.mjs",import.meta.url).pathname,protocol={id:"casebook-persistence-json",version:1};
const A="case:11111111-1111-4111-8111-111111111111",B="case:22222222-2222-4222-8222-222222222222",K="knowledge:33333333-3333-4333-8333-333333333333",ALIAS="alias:44444444-4444-4444-8444-444444444444";
const invoke=(cwd,r)=>new Promise(resolve=>{const p=execFile(process.execPath,[bin],{cwd,env:{PATH:process.env.PATH??"",HOME:cwd}},(e,out,err)=>resolve({code:e?2:0,json:JSON.parse(out),err}));p.stdin.end(JSON.stringify(r));});
const record=(id,ns,title)=>({id,home_namespace_id:ns,state:"active",title,summary:"contract",scope:"test",aliases:[],facets:[],entries:[],sources:[],relationships:[],references:[]});
async function setup(){const root=await mkdtemp(path.join(os.tmpdir(),"l02-w04-")),configuration={source:{kind:"test",locator:"w04"},authority_mode:"sqlite",sqlite:{database_url:path.join(root,"db"),sqlite_bin:await selectCompatibleSqliteBinary()}},init=await invoke(root,{protocol,operation:"initialize_store",operation_id:"operation:init",authority_claim:{human_authorized:true,acting_role:"test",authority_basis:"test"},configuration});assert.equal(init.code,0,JSON.stringify(init.json));const i=init.json.result.initialization,context={view_id:i.view.id,view_policy_revision_id:i.view.policy_revision_id,purpose:"w04",requested_audience_ceiling:"private"};return{root,configuration,common:{protocol,request_version:1,store_id:i.store_id,context,configuration},ns:i.namespace.id};}
const commit=(s,operation,id,expected,value)=>invoke(s.root,{...s.common,operation,operation_id:id,expected_revision:expected,commit_basis:"test",provenance:{acting_role:"test"},case:value});
test("historical observed and pinned references retain identity and expose drift without forced rewrite",async()=>{const s=await setup();try{const target=record(B,s.ns,"target"),t1=await commit(s,"case.create","operation:t1",0,target);assert.equal(t1.code,0);const owner=record(A,s.ns,"owner");owner.references=[{target_kind:"case",target_id:B,observed_revision_id:t1.json.result.revision.id,pinned_revision_id:t1.json.result.revision.id,predicate:"references",visibility:"private"}];assert.equal((await commit(s,"case.create","operation:o1",0,owner)).code,0);target.title="advanced";assert.equal((await commit(s,"case.commit_revision","operation:t2",1,target)).code,0);const read=await invoke(s.root,{...s.common,operation:"case.read",case_id:A});assert.equal(read.code,0,JSON.stringify(read.json));const ref=read.json.result.case.references[0];assert.equal(ref.observed_revision_id,t1.json.result.revision.id);assert.equal(ref.pinned_revision_id,t1.json.result.revision.id);assert.equal(ref.reference_state,"pinned-drift");assert.notEqual(ref.current_target_revision_id,ref.pinned_revision_id);assert.equal((await commit(s,"case.commit_revision","operation:o2",1,read.json.result.case)).code,0);const traversal=await invoke(s.root,{...s.common,operation:"case.traverse",start_case_ids:[A],predicates:[],direction:"outgoing",max_depth:2,node_limit:10});assert.equal(traversal.json.result.edges[0].reference_state,"pinned-drift");}finally{await rm(s.root,{recursive:true,force:true});}});

test("subobject references use the visible owning Case history and alias reads share annotation",async()=>{const s=await setup();try{const target=record(B,s.ns,"target");target.aliases=[{id:ALIAS,state:"active",version:{value:"Target Alias",kind:"name"}}];target.entries=[{id:K,state:"active",version:{display_label:"K",title:"knowledge",purpose:"test",classification:"accepted",body:"body",provenance:{acting_role:"test"},positions:[],relationships:[],references:[]}}];const t1=await commit(s,"case.create","operation:family-t1",0,target);assert.equal(t1.code,0,JSON.stringify(t1.json));const owner=record(A,s.ns,"owner");owner.references=[{target_kind:"knowledge",target_id:K,observed_revision_id:t1.json.result.revision.id,predicate:"supports",visibility:"private"}];assert.equal((await commit(s,"case.create","operation:family-o1",0,owner)).code,0);target.summary="advanced";const t2=await commit(s,"case.commit_revision","operation:family-t2",1,target);assert.equal(t2.code,0);const read=await invoke(s.root,{...s.common,operation:"case.read",case_id:A}),ref=read.json.result.case.references[0];assert.deepEqual(ref.target_family,{kind:"knowledge",id:K});assert.equal(ref.owning_case_id,B);assert.equal(ref.current_owner_revision_id,t2.json.result.revision.id);assert.equal(ref.reference_state,"stale");const alias=await invoke(s.root,{...s.common,operation:"case.resolve",alias:{namespace_id:s.ns,value:"TARGET ALIAS",kind:"name"}});assert.equal(alias.code,0,JSON.stringify(alias.json));assert.equal(alias.json.result.case_id,B);}finally{await rm(s.root,{recursive:true,force:true});}});

test("tombstoned selected subobject families become dangling and reject new references atomically",async()=>{const s=await setup();try{const target=record(B,s.ns,"target");target.entries=[{id:K,state:"active",version:{display_label:"K",title:"knowledge",purpose:"test",classification:"accepted",body:"body",provenance:{acting_role:"test"},positions:[],relationships:[],references:[]}}];const t1=await commit(s,"case.create","operation:deleted-t1",0,target);assert.equal(t1.code,0,JSON.stringify(t1.json));const owner=record(A,s.ns,"owner");owner.references=[{target_kind:"knowledge",target_id:K,observed_revision_id:t1.json.result.revision.id,predicate:"supports",visibility:"private"}];assert.equal((await commit(s,"case.create","operation:deleted-o1",0,owner)).code,0);target.entries[0].state="tombstoned";const deleted=await commit(s,"case.commit_revision","operation:deleted-t2",1,target);assert.equal(deleted.code,0,JSON.stringify(deleted.json));const dangling=await invoke(s.root,{...s.common,operation:"case.read",case_id:A});assert.equal(dangling.code,2,JSON.stringify(dangling.json));assert.equal(dangling.json.failure.code,"case.semantic_reconcile_required");assert.equal(dangling.json.failure.evidence.semantic_evidence.mutation_performed,false);assert.equal(dangling.json.failure.evidence.semantic_evidence.violations[0].rule,"reference_target_not_visible");const newcomer=record("case:55555555-5555-4555-8555-555555555555",s.ns,"new owner");newcomer.references=[{target_kind:"knowledge",target_id:K,observed_revision_id:deleted.json.result.revision.id,predicate:"supports",visibility:"private"}];const rejected=await commit(s,"case.create","operation:deleted-new",0,newcomer);assert.equal(rejected.code,2,JSON.stringify(rejected.json));assert.equal(rejected.json.failure.evidence.violations[0].rule,"reference_target_not_visible");const absent=await invoke(s.root,{...s.common,operation:"case.read",case_id:newcomer.id});assert.equal(absent.code,2);assert.equal(absent.json.failure.code,"case.not_found_or_not_visible");}finally{await rm(s.root,{recursive:true,force:true});}});

test("semantically invalid Markdown is staged as typed evidence without mutation while binding tampering fails",async()=>{const s=await setup();try{assert.equal((await commit(s,"case.create","operation:md-create",0,record(A,s.ns,"markdown"))).code,0);const rendered=(await invoke(s.root,{...s.common,operation:"case.markdown.render",case_id:A,audience:"private",evidence_selection:[]})).json.result,before=rendered.revision.id,request={...s.common,operation:"case.markdown.stage_reconciliation",case_id:A,base_revision:{id:before,number:1},original_manifest:rendered.manifest,original_digest:rendered.digest};const invalid=rendered.markdown.replace('"title": "markdown"','"title": ""'),staged=await invoke(s.root,{...request,edited_markdown:invalid});assert.equal(staged.code,0,JSON.stringify(staged.json));assert.equal(staged.json.result.semantic_evidence.kind,"case.semantic_evidence");assert.equal(staged.json.result.semantic_evidence.mutation_performed,false);assert.equal(staged.json.result.disposition,"requires-semantic-reconcile");assert.equal((await invoke(s.root,{...s.common,operation:"case.read",case_id:A})).json.result.revision.id,before);const tampered=rendered.markdown.replace("audience: private","audience: portable");assert.equal((await invoke(s.root,{...request,edited_markdown:tampered})).code,2);}finally{await rm(s.root,{recursive:true,force:true});}});
