-- Casebook persistence schema identity: casebook-persistence-sqlite@3.
-- New stores begin at the current ordinary-access schema. Legacy schema-v1.sql
-- is retained exclusively for disposable migration-source rehearsal.
PRAGMA foreign_keys = ON;

CREATE TABLE store_metadata (singleton INTEGER PRIMARY KEY CHECK (singleton = 1), store_id TEXT NOT NULL UNIQUE, schema_id TEXT NOT NULL, schema_version INTEGER NOT NULL CHECK (schema_version > 0), protocol_id TEXT NOT NULL, protocol_version INTEGER NOT NULL CHECK (protocol_version > 0), initialized_at TEXT NOT NULL, initialization_operation_id TEXT NOT NULL) STRICT;
CREATE TRIGGER store_metadata_immutable_update BEFORE UPDATE ON store_metadata BEGIN SELECT RAISE(ABORT, 'store metadata is immutable'); END;
CREATE TRIGGER store_metadata_immutable_delete BEFORE DELETE ON store_metadata BEGIN SELECT RAISE(ABORT, 'store metadata is immutable'); END;
CREATE TABLE store_authority_binding (singleton INTEGER PRIMARY KEY CHECK (singleton = 1), store_id TEXT NOT NULL UNIQUE REFERENCES store_metadata(store_id), source_kind TEXT NOT NULL, source_locator TEXT NOT NULL, authority_mode TEXT NOT NULL CHECK (authority_mode = 'sqlite'), bound_at TEXT NOT NULL, binding_operation_id TEXT NOT NULL) STRICT;
CREATE TRIGGER store_authority_binding_immutable_update BEFORE UPDATE ON store_authority_binding BEGIN SELECT RAISE(ABORT, 'store authority binding is immutable; switching requires migration'); END;
CREATE TRIGGER store_authority_binding_immutable_delete BEFORE DELETE ON store_authority_binding BEGIN SELECT RAISE(ABORT, 'store authority binding is immutable; switching requires migration'); END;
CREATE TABLE namespaces (namespace_id TEXT PRIMARY KEY, namespace_key TEXT NOT NULL UNIQUE, lifecycle TEXT NOT NULL CHECK (lifecycle IN ('active', 'retired')), created_at TEXT NOT NULL) STRICT;
CREATE TABLE store_fence (singleton INTEGER PRIMARY KEY CHECK (singleton = 1), operation_fence INTEGER NOT NULL CHECK (operation_fence >= 0)) STRICT;
CREATE TABLE store_operation_receipts (operation_id TEXT PRIMARY KEY, operation_kind TEXT NOT NULL, store_id TEXT NOT NULL REFERENCES store_metadata(store_id), request_digest TEXT NOT NULL, outcome TEXT NOT NULL, result_json TEXT NOT NULL CHECK (json_valid(result_json)), result_digest TEXT NOT NULL, authority_claim_json TEXT NOT NULL CHECK (json_valid(authority_claim_json)), settled_at TEXT NOT NULL, failure_class TEXT, retry_disposition TEXT NOT NULL CHECK (retry_disposition IN ('never', 'after_reconcile', 'after_operator_repair')), operation_fence INTEGER NOT NULL CHECK (operation_fence > 0), owner_id TEXT, owner_kind TEXT, owner_home_namespace_id TEXT REFERENCES namespaces(namespace_id), expected_revision INTEGER CHECK (expected_revision IS NULL OR expected_revision >= 0), observed_revision INTEGER CHECK (observed_revision IS NULL OR observed_revision >= 0), committed_revision INTEGER CHECK (committed_revision IS NULL OR committed_revision > 0), event_id TEXT, snapshot_sha256 TEXT, snapshot_size_bytes INTEGER CHECK (snapshot_size_bytes IS NULL OR snapshot_size_bytes > 0)) STRICT;
CREATE TRIGGER store_operation_receipts_immutable_update BEFORE UPDATE ON store_operation_receipts BEGIN SELECT RAISE(ABORT, 'store operation receipts are immutable'); END;
CREATE TRIGGER store_operation_receipts_immutable_delete BEFORE DELETE ON store_operation_receipts BEGIN SELECT RAISE(ABORT, 'store operation receipts are immutable'); END;
CREATE TABLE owners (owner_id TEXT PRIMARY KEY, owner_kind TEXT NOT NULL, home_namespace_id TEXT NOT NULL REFERENCES namespaces(namespace_id), created_at TEXT NOT NULL, UNIQUE (owner_id, owner_kind)) STRICT;
CREATE TRIGGER owners_identity_immutable BEFORE UPDATE OF owner_id, owner_kind ON owners BEGIN SELECT RAISE(ABORT, 'owner identity is immutable'); END;
CREATE TABLE owner_placement_events (placement_event_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(owner_id), from_namespace_id TEXT NOT NULL REFERENCES namespaces(namespace_id), to_namespace_id TEXT NOT NULL REFERENCES namespaces(namespace_id), operation_id TEXT NOT NULL UNIQUE, operation_fence INTEGER NOT NULL UNIQUE CHECK (operation_fence > 0), authority_claim_json TEXT NOT NULL CHECK (json_valid(authority_claim_json)), committed_at TEXT NOT NULL) STRICT;
CREATE TRIGGER owner_placement_events_immutable_update BEFORE UPDATE ON owner_placement_events BEGIN SELECT RAISE(ABORT, 'owner placement events are immutable'); END;
CREATE TRIGGER owner_placement_events_immutable_delete BEFORE DELETE ON owner_placement_events BEGIN SELECT RAISE(ABORT, 'owner placement events are immutable'); END;
CREATE TABLE owner_family_bindings (family_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(owner_id), created_at TEXT NOT NULL, UNIQUE (family_id, owner_id)) STRICT;
CREATE TABLE owner_versions (version_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(owner_id), family_id TEXT NOT NULL REFERENCES owner_family_bindings(family_id), content_json TEXT NOT NULL CHECK (json_valid(content_json)), content_digest TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE (owner_id, family_id, version_id), FOREIGN KEY (family_id, owner_id) REFERENCES owner_family_bindings(family_id, owner_id)) STRICT;
CREATE TABLE owner_revisions (revision_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(owner_id), revision_number INTEGER NOT NULL CHECK (revision_number > 0), normalized_json TEXT NOT NULL CHECK (json_valid(normalized_json)), representation_id TEXT NOT NULL, representation_version INTEGER NOT NULL CHECK (representation_version > 0), operation_id TEXT NOT NULL UNIQUE, committed_at TEXT NOT NULL, UNIQUE (owner_id, revision_number)) STRICT;
CREATE TABLE owner_revision_selections (revision_id TEXT NOT NULL REFERENCES owner_revisions(revision_id), family_id TEXT NOT NULL, version_id TEXT NOT NULL REFERENCES owner_versions(version_id), PRIMARY KEY (revision_id, family_id)) STRICT, WITHOUT ROWID;
CREATE TABLE owner_current (owner_id TEXT PRIMARY KEY REFERENCES owners(owner_id), revision_id TEXT NOT NULL REFERENCES owner_revisions(revision_id), revision_number INTEGER NOT NULL CHECK (revision_number > 0), projection_json TEXT NOT NULL CHECK (json_valid(projection_json)), updated_at TEXT NOT NULL) STRICT;
CREATE TABLE owner_events (event_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(owner_id), owner_kind TEXT NOT NULL, owner_revision_id TEXT NOT NULL REFERENCES owner_revisions(revision_id), owner_revision INTEGER NOT NULL CHECK (owner_revision > 0), namespace_id TEXT NOT NULL REFERENCES namespaces(namespace_id), event_type TEXT NOT NULL, event_schema_version INTEGER NOT NULL CHECK (event_schema_version > 0), operation_id TEXT NOT NULL UNIQUE, causation TEXT, correlation TEXT, commit_sequence INTEGER NOT NULL UNIQUE CHECK (commit_sequence > 0), committed_at TEXT NOT NULL, visibility_ceiling TEXT NOT NULL CHECK (visibility_ceiling = 'private'), payload_json TEXT NOT NULL CHECK (json_valid(payload_json)), payload_digest TEXT NOT NULL) STRICT;
CREATE TABLE owner_outbox (outbox_id TEXT PRIMARY KEY, operation_id TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES owners(owner_id), outbox_kind TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)), payload_digest TEXT NOT NULL, commit_sequence INTEGER NOT NULL REFERENCES owner_events(commit_sequence), created_at TEXT NOT NULL) STRICT;
CREATE TABLE event_retention (singleton INTEGER PRIMARY KEY CHECK (singleton = 1), retained_after_sequence INTEGER NOT NULL CHECK (retained_after_sequence >= 0)) STRICT;
CREATE TABLE schema_migrations (migration_id TEXT PRIMARY KEY, schema_id TEXT NOT NULL, from_version INTEGER NOT NULL CHECK (from_version >= 0), to_version INTEGER NOT NULL CHECK (to_version > from_version), schema_asset_digest TEXT NOT NULL, migration_manifest_digest TEXT NOT NULL, operation_id TEXT NOT NULL REFERENCES store_operation_receipts(operation_id), applied_at TEXT NOT NULL) STRICT;
CREATE TRIGGER schema_migrations_immutable_update BEFORE UPDATE ON schema_migrations BEGIN SELECT RAISE(ABORT, 'schema migration ledger is immutable'); END;
CREATE TRIGGER schema_migrations_immutable_delete BEFORE DELETE ON schema_migrations BEGIN SELECT RAISE(ABORT, 'schema migration ledger is immutable'); END;
CREATE TABLE migration_archives (archive_id TEXT PRIMARY KEY, migration_id TEXT NOT NULL, archive_json TEXT NOT NULL CHECK (json_valid(archive_json)), archived_at TEXT NOT NULL, operation_id TEXT NOT NULL UNIQUE) STRICT;
